# Generated by Django 3.1.1 on 2020-10-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fints_downloader', '0003_remove_logincredentials_tan_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLogin',
            fields=[
                ('id', models.CharField(help_text='ID containing the hashed business key', max_length=64, primary_key=True, serialize=False)),
                ('bk_id', models.CharField(help_text='Unhashed business key', max_length=1024)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(blank=True, help_text='Decribing name of credentials', max_length=1024, null=True)),
                ('user_id', models.CharField(help_text='Login/user name', max_length=1024)),
                ('password', models.CharField(help_text='Password or pin for this account', max_length=1024)),
                ('tan_mechanism', models.CharField(blank=True, help_text='Default TAN mechanism', max_length=3, null=True)),
                ('bic', models.CharField(help_text='Bank identifier code', max_length=11)),
                ('code', models.DecimalField(decimal_places=0, help_text='German bank code', max_digits=8)),
                ('server', models.CharField(help_text='Bank fints server connection string', max_length=1024)),
            ],
            options={
                'ordering': ['bk_id'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='logincredentials',
            name='bank',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['bk_id']},
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='not_both_null',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='login_credentials',
        ),
        migrations.AddField(
            model_name='account',
            name='bic',
            field=models.CharField(blank=True, help_text='Bank identifier code', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Account number', max_digits=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='LoginCredentials',
        ),
        migrations.AddField(
            model_name='account',
            name='bank_login',
            field=models.ForeignKey(blank=True, help_text='Login credentials used for this account', null=True, on_delete=django.db.models.deletion.CASCADE, to='fints_downloader.banklogin'),
        ),
    ]
