# Generated by Django 3.1.1 on 2020-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fints_downloader', '0004_auto_20201011_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinTSDownloaderBackend',
            fields=[
                ('id', models.CharField(help_text='ID containing the hashed business key', max_length=64, primary_key=True, serialize=False)),
                ('bk_id', models.CharField(help_text='Unhashed business key', max_length=1024)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(help_text='Name of backend', max_length=1024)),
                ('server', models.CharField(help_text='Server address of FinTS downloader backend', max_length=1024)),
                ('port', models.PositiveIntegerField(default=80, help_text='Server port of FinTS downloader backend')),
                ('base_url', models.CharField(blank=True, help_text='Base url of endpoint', max_length=1024)),
            ],
            options={
                'ordering': ['bk_id'],
                'abstract': False,
            },
        ),
    ]
