# Generated by Django 3.1.1 on 2020-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fints_downloader', '0005_fintsdownloaderbackend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fintsdownloaderbackend',
            options={},
        ),
        migrations.RemoveField(
            model_name='fintsdownloaderbackend',
            name='bk_id',
        ),
        migrations.RemoveField(
            model_name='fintsdownloaderbackend',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='fintsdownloaderbackend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fintsdownloaderbackend',
            name='name',
            field=models.CharField(help_text='Name of backend', max_length=1024, unique=True),
        ),
    ]
