# Generated by Django 3.1.1 on 2020-10-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fints_downloader', '0007_auto_20201017_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='init_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial account balance', max_digits=32),
        ),
    ]
