# Generated by Django 3.1.1 on 2020-10-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fints_downloader', '0008_account_init_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=1024)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='bk_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fints_downloader.category'),
        ),
    ]
