# Generated by Django 3.1.1 on 2021-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fints_downloader', '0009_auto_20201025_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='banklogin',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is this bank login enabled'),
        ),
        migrations.AddField(
            model_name='banklogin',
            name='tan_required',
            field=models.BooleanField(default=False, help_text='Last automatic access required a TAN'),
        ),
    ]
