# Generated by Django 3.1.1 on 2021-01-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fints_downloader', '0010_auto_20210109_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
