[template]
src = "ldap.conf.tmpl"
dest = "/etc/openldap/ldap.conf"
keys = [
    "/conf/ldap/base_dn",
    "/conf/ldap/uri",
    "/conf/ldap/tls_reqcert",
    "/conf/ldap/tls_cacert",
]
reload_cmd = "supervisorctl restart gunicorn"
